---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gce
  name: php-apache-ing
spec:
  backend:
    serviceName: php-apache-svc
    servicePort: 80