---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"grpc-routeguide":"HTTP2"}'
  name: routeguide-svc
spec:
  externalTrafficPolicy: Local
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: routeguide-dep
spec:
  replicas: 2
  template:
    spec:
      containers:
      # [START app_container]
      - name: routeguide
        image: gcr.io/nmiu-play/go-routeguide:latest
        imagePullPolicy: Always
        ports:
        - name: grpc-routeguide
          containerPort: 10000
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 300Mi
        command:
        - /server
        args: 
        - --cert_file=/data/tls.crt
        - --key_file=/data/tls.key
        - --port=10000
        - --tls
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: true
        # [END app_container]
      volumes:
      - name: data
        secret:
          secretName: premium-cloud-support-com-tls

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: routeguide-ing
  annotations:
    kubernetes.io/ingress.global-static-ip-name: asuka
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: false 
spec:
  backend:
  tls:
  - hosts:
    - asuka.premium-cloud-support.com
    secretName: premium-cloud-support-com-tls
  rules:
  - host: asuka.premium-cloud-support.com
    http:
      paths:
      - backend:
          serviceName: routeguide-svc
          servicePort: 10000
        path: /*


---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: routeguide-client
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          # [START app_container]
          - name: routeguide-client
            image: gcr.io/nmiu-play/go-routeguide:latest
            command:
            - /client
            args:
            - --server_addr=routeguide-svc:10000
            - --ca_file=/data/tls.crt
            - --server_host_override=asuka.premium-cloud-support.com
            - --tls
            volumeMounts:
            - name: data
              mountPath: /data
              readOnly: true
          restartPolicy: OnFailure
          # [END app_container]
          volumes:
          - name: data
            secret:
              secretName: premium-cloud-support-com-tls
