---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    deployment: php-apache
  name: php-apache-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      serviceAccountName: client ## the SA granted with PSP
      containers:
      - image: gcr.io/nmiu-play/php-apache
        imagePullPolicy: Always
        name: php-apache
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi

