---
apiVersion: v1
kind: Service
metadata:
  name: routeguide-svc
spec:
  ports:
  - name: grpc-routeguide
    port: 10000
    targetPort: 10000
  selector:
    app: routeguide

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: routeguide-dep
  labels:
    deployment: routeguide
spec:
  replicas: 2
  selector:
    matchLabels:
      app: routeguide
  template:
    metadata:
      labels:
        app: routeguide
    spec:
      containers:
      - name: routeguide
        image: gcr.io/nmiu-play/go-routeguide:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc-routeguide
          containerPort: 10000
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 300Mi