---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-controller-sa

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sample-controller-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: sample-controller-sa
    namespace: default

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-controller-dep
  labels:
    deployment: sample-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-controller
  template:
    metadata:
      labels:
        app: sample-controller
    spec:
      containers:
      - name: sample-controller
        image: gcr.io/nmiu-play/sample-controller:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 300Mi
      serviceAccountName: sample-controller-sa