apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  name: go-web-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 10443
  selector:
    app: go-web
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  ports:
  - name: mongo
    port: 27017
  selector:
    app: mongodb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    deployment: go-web
  name: go-web-dep
spec:
  minReadySeconds: 60
  replicas: 2
  selector:
    matchLabels:
      app: go-web
  template:
    metadata:
      labels:
        app: go-web
    spec:
      containers:
      - env:
        - name: MONGODB_URL
          value: mongodb-svc
        image: gcr.io/nmiu-play/go-web
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /liveness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: go-web
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 10443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /readiness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z mongodb-svc 27017; do sleep 2; done
        image: busybox
        name: wait-for-db
      terminationGracePeriodSeconds: 90
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    deployment: mongodb
  name: mongodb-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: gcr.io/nmiu-play/mongodb:latest
        imagePullPolicy: IfNotPresent
        name: mongodb
        ports:
        - containerPort: 27017
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gce
  name: go-web-ing
spec:
  backend:
    serviceName: go-web-svc
    servicePort: 80