---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx-dep
spec:
  replicas: 1
  template:
    spec:
      volumes:
       - name: data
         persistentVolumeClaim:
           claimName: rwo-pvc
      containers:
      # [START app_container]
      - name: nginx
        volumeMounts:
          - name: data
            mountPath: /usr/share/nginx/html
      # [END app_container]
      initContainers:
      - name: init-index
        image: busybox
        command: ['sh', '-c', 'echo "Hello from PD!" > /data/index.html']
        volumeMounts:
          - name: data
            mountPath: /data/