---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-web-ing
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "asuka"
    kubernetes.io/ingress.class: gce
spec:
  tls:
  - secretName: go-web-tls
