apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/nmiu-play/nm-php-apache
deploy:
  kubectl:
    manifests:
      - ../k8s/deployment.yaml
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: nmiu-play
