apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: premium-cloud-support-com
  namespace: default
spec:
  secretName: premium-cloud-support-com-tls
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
  commonName: 'premium-cloud-support.com'
  dnsNames:
  - premium-cloud-support.com
  acme:
    config:
    - dns01:
        provider: cloud-dns
      domains:
      - premium-cloud-support.com
      - '*.premium-cloud-support.com'
      