{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fortio.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fortio.name" . }}
    chart: {{ template "fortio.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- end }}