---
apiVersion: v1
kind: Pod
metadata:
  name: hammer
  labels:
    app: hammer
spec:
  containers:
  # [START app_container]
  - name: hammer
    image: gcr.io/nmiu-play/hammer
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 128Mi
  # [END app_container]
