---
kind: Service
apiVersion: v1
metadata:
  name: go-web-svc
spec:
  externalTrafficPolicy: Cluster
  # type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-web-dep
spec:
  template:
    spec:
      containers:
      - name: go-web
        env:
        - name: MONGODB_URL
          value: mongodb-svc
      initContainers:
      - name: wait-for-mongodb
        image: busybox
        command: ['sh', '-c', 'until nc -z mongodb-svc 27017; do sleep 2; done']

