---
apiVersion: v1
kind: Deployment
metadata:
  name: hey
  labels:
    app: hey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hey
  template:
    metadata:
      labels:
        app: hey
    spec:
      containers:
      # [START app_container]
      - name: hey
        image: gcr.io/nmiu-play/hey
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        command:
        - /bin/sh
        - -c
        - while :; do sleep 10; done
      # [END app_container]
