---
apiVersion: v1
kind: Pod
metadata:
  name: hey
  labels:
    app: hey
spec:
  containers:
  # [START app_container]
  - name: hey
    image: gcr.io/nmiu-play/hey
    imagePullPolicy: Always
    command:
      - "/bin/sh"
      - "-c"
      - "while true; do sleep 5; done"
  # [END app_container]
