---
apiVersion: v1
data:
  concurrent_requests: "10"
  requests: "100"
kind: ConfigMap
metadata:
  name: hey-config

---
apiVersion: v1
data:
  url: aHR0cDovLzE2OS4yNTQuMTY5LjI1NC9jb21wdXRlTWV0YWRhdGEvdjEvaW5zdGFuY2Uvc2VydmljZS1hY2NvdW50cy9kZWZhdWx0L3Rva2VuCg==
kind: Secret
metadata:
  name: hey-secret

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hey
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hey
            image: gcr.io/nmiu-play/hey
            env:
            - name: URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: hey-secret
            - name: REQUESTS
              valueFrom:
                configMapKeyRef:
                  key: requests
                  name: hey-config
            - name: CONCURRENT_REQUESTS
              valueFrom:
                configMapKeyRef:
                  key: concurrent_requests
                  name: hey-config
            command:
            - "/bin/sh"
            - "-c"
            - '/hey -n $REQUESTS -c $CONCURRENT_REQUESTS -H "Metadata-Flavor:Google" $URL'
          restartPolicy: Never
