---
# Cloud SQL Proxy makes requests to google apis
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: oauth2.googleapis.com
  namespace: istio-workload
spec:
  hosts:
    - oauth2.googleapis.com
    - www.googleapis.com
  ports:
    - name: https
      number: 443
      protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
