---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: php-apache-ing
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  backend:
    serviceName: php-apache-svc
    servicePort: 80
