apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: premium-cloud-support.com
  namespace: default
spec:
  secretName: premium-cloud-support-com-tls
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
  commonName: premium-cloud-support.com
  dnsNames:
  - premium-cloud-support.com
  - asuka.premium-cloud-support.com