kind: Service
apiVersion: v1
metadata:
  name: svc
spec:
  selector:
    app: php
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
  type: NodePort
  externalTrafficPolicy: Cluster
