---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: routeguide-ing
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  backend:
    serviceName: routeguide-svc
    servicePort: 10000
