apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nm-php-apache-ing
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  # tls:
    # - secretName: php-tls
  backend:
    serviceName: nm-php-apache-svc
    servicePort: 80
