---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: php-apache-dep
spec:
  replicas: 2
  template:
    spec:
      volumes:
       - name: data
         persistentVolumeClaim:
           claimName: rox-pvc
           readOnly: true 
      containers:
      # [START app_container]
      - name: php-apache
        volumeMounts:
          - name: data
            mountPath: /var/www/html/
      # [END app_container]