---
apiVersion: v1
kind: PersistentVolume
metadata:
  name : rox-pv
spec:
  accessModes:
    - ReadOnlyMany
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: ext4
    pdName: test-disk
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: rox-pvc
spec:
  accessModes:
    - ReadOnlyMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
