apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nm-php-apache-dep
  labels:
    deployment: nm-php-apache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nm-php-apache
    spec:
      containers:
        - name: nm-php-apache
          image: gcr.io/nmiu-play/nm-php-apache
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
              
              
