apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: runner
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: runner
            image: gcr.io/nmiu-play/toolbox
            env:
            - name: URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: cronjob-secret
            - name: USER_AGENT
              valueFrom:
                secretKeyRef:
                  key: user_agent
                  name: cronjob-secret
            command:
            - '/bin/sh'
            - '-c'
            - >
              for i in `seq 100`; do
                curl -s -H "${USER_AGENT}" $URL > /dev/null;
                sleep 1;
              done;
          restartPolicy: Never
