---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-impersonater
rules:
- apiGroups: [""]
  resources: ["users", "groups"]
  verbs: ["impersonate"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-impersonater
subjects:
- kind: ServiceAccount
  name: client
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-impersonater
  apiGroup: rbac.authorization.k8s.io
