---
kind: Service
apiVersion: v1
metadata:
  name: svc
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: NodePort

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dep
  labels:
    deployment: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      # [START app_container]
      - name: nginx
        image: gcr.io/nmiu-play/nginx
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
      # [END app_container]