##################################################################################################
# frontend service
##################################################################################################

---
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      # [START app_container]
      - name: frontend
        image: gcr.io/nmiu-play/go-web:latest
        imagePullPolicy: Always
        args: ["-backend", "backend:8000"]
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: https
          containerPort: 10443
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          # httpGet:
          #   path: /liveness
          #   port: 8000
          #   scheme: HTTP
          exec: # mTLS is blocking kubelet from reaching the probes on the app serving port (https://github.com/istio/istio/issues/2628)
            command:
            - /bin/sh
            - -c
            - curl localhost:8000/liveness
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          # httpGet:
          #   path: /readiness
          #   port: 8000
          #   scheme: HTTP
          exec:
            command:
            - /bin/sh
            - -c
            - curl localhost:8000/readiness
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      # [START app_container]


##################################################################################################
# backend service
##################################################################################################
---
kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      # [START app_container]
      - name: backend
        image: gcr.io/nmiu-play/go-web:latest
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: "v1"
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: https
          containerPort: 10443
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl localhost:8000/liveness
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl localhost:8000/readiness
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      # [START app_container]

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      containers:
      # [START app_container]
      - name: backend
        image: gcr.io/nmiu-play/go-web:latest
        imagePullPolicy: Always
        env:
        - name: MONGODB_URL
          value: mongodb
        - name: VERSION
          value: "v2"
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: https
          containerPort: 10443
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl localhost:8000/liveness
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl localhost:8000/readiness
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      # [START app_container]
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z mongodb 27017; do sleep 2; done']

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - port: 27017
    name: mongo
  selector:
    app: mongodb

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb 
        image: gcr.io/nmiu-play/mongodb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
