---
kind: Service
apiVersion: v1
metadata:
  name: svc
spec:
  externalTrafficPolicy: Local

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
  rules:
    - http:
        paths:
          - path: /test
            backend:
              serviceName: nic-svc # namePrefix: nic-
              servicePort: 80