---
kind: Service
apiVersion: v1
metadata:
  name: go-web-svc
spec:
  selector:
    app: go-web
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: https
    protocol: TCP
    port: 10443
    targetPort: 10443
  type: NodePort
  externalTrafficPolicy: Local # or Cluster

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-web-dep
  labels:
    deployment: go-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-web
  template:
    metadata:
      labels:
        app: go-web
    spec:
      containers:
      # [START app_container]
      - name: go-web
        image: gcr.io/nmiu-play/go-web
        imagePullPolicy: Always
        env:
        - name: MONGODB_URL
          value: mongodb-svc
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 300Mi
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: https
          containerPort: 10443
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      # [START app_container]
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z mongodb-svc 27017; do sleep 2; done']

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  ports:
  - port: 27017
    name: mongo
  selector:
    app: mongodb

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-dep
  labels:
    deployment: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb 
        image: gcr.io/nmiu-play/mongodb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 300m
            memory: 1Gi
            ephemeral-storage: 2Gi
          limits:
            cpu: 300m
            memory: 1Gi
            ephemeral-storage: 2Gi