---
kind: Service
apiVersion: v1
metadata:
  name: php-apache-svc
spec:
  selector:
    app: php-apache
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-apache-dep
  labels:
    deployment: php-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      # [START app_container]
      - name: php-apache
        image: gcr.io/nmiu-play/php-apache
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
      # [END app_container]
