---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  containers:
  # [START app_container]
  - name: toolbox
    image: gcr.io/nmiu-play/toolbox
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 128Mi
  # [END app_container]
