apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  containers:
  - image: gcr.io/nmiu-play/toolbox
    imagePullPolicy: Always
    name: toolbox
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
    - name: data
      mountPath: "/data"
  volumes:
  - name: foo
    secret:
      secretName: premium-cloud-support-com-tls
  - name: data
    persistentVolumeClaim:
      claimName: test-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: test-pvc
spec:
  accessModes:
    - ReadOnlyMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
