---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-web-ing
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "asuka"
    kubernetes.io/ingress.class: gce
spec:
  backend:
  tls:
  - hosts:
    - asuka.premium-cloud-support.com
    secretName: premium-cloud-support-com-tls
  rules:
  - host: asuka.premium-cloud-support.com
    http:
      paths:
      - backend:
          serviceName: go-web
          servicePort: 80
        path: /*