steps:
  - name: "gcr.io/cloud-builders/git"
    args:
      [
        "clone",
        "https://github.com/AskMediaGroup/dnsbench.git",
        "src/github.com/askcom/dnsbench",
      ]
  - name: "gcr.io/cloud-builders/go:debian"
    args: ["install", "github.com/askcom/dnsbench/cmd/${_APP_NAME_}"]
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "cp", "bin/${_APP_NAME_}", "gs://${_BUCKET_NAME_}/"]
substitutions:
  _APP_NAME_: dnsbench
  _BUCKET_NAME_: nmiu-play_tools
