---
apiVersion: v1
kind: Pod
metadata:
  name: hammer
spec:
  containers:
    # [START app_container]
    - name: hammer
      volumeMounts:
        - name: data
          mountPath: /data
    # [END app_container]
  volumes:
    - name: data
      gcePersistentDisk:
        pdName: test-disk
        fsType: ext4
