---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-v1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      # [START app_container]
      - name: helloworld
        image: istio/playbooks-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 500
      # [END app_container]