---
apiVersion: v1
kind: Service
metadata:
  name: nginx-statefulset-svc
spec:
  selector:
    app: web
  ports:
  - port: 80
    name: http
  type: LoadBalancer

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: nginx-statefulset-svc
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web
            topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: gcr.io/nmiu-play/nginx
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: init-index
        image: busybox
        command: ['sh', '-c', 'echo `hostname` > /data/index.html']
        volumeMounts:
        - name: www
          mountPath: /data/
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
