---
apiVersion: v1
kind: Pod
metadata:
  name: hammer
spec:
  serviceAccountName: client
  automountServiceAccountToken: false
  containers:
  - name: hammer
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: client-secret
