---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: default-reader
rules:
- apiGroups: ["", "extensions"] # "" indicates the core API group
  resources: ["pods", "deployments", "replicasets"]
  verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-stuff
  namespace: default
subjects:
- kind: ServiceAccount
  name: client # Name is case sensitive
  namespace: default
- kind: Group
  name: nm-k8s-rbac@google.com # google group
  namespace: default
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: default-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
