---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
automountServiceAccountToken: false

---
apiVersion: v1
kind: Secret
metadata:
  name: client-secret
  annotations:
    kubernetes.io/service-account.name: client
type: kubernetes.io/service-account-token